# Generated by Django 4.2.4 on 2024-02-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('intime', models.CharField(max_length=100)),
                ('outtime', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stdent_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('joining_date', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Saveform',
        ),
    ]
